### ISSUE TITLE
Does file name as file path invade privacy?

### ISSUE THREAD

**Issue by mxcop** [emberry-org/smoke#1]
Sending the entire file path along with the file might invade privacy.
Because sometimes a path may contain `/home/<user>/` or some other sensitive information.
https://github.com/emberry-org/smoke/blob/cfb097e268e31a5acd84aefdd8ef1e135f69852b/src/messages/splitter.rs#L47

I suggest we instead use: *(unless I'm wrong and the path can never contain sensitive info)*
```rs
pub fn file_name(&self) -> Option<&OsStr>
```

**Comment by devensiv** [comment]
good observation. we should indeed only use the filename or smth like that to avoid leaking local paths.
we need to make sure however that we do not transmit two different files using the same identifier concurrently

**Comment by mxcop** [comment]
Issue was fixed in commit: 76a0745
